name: loggregator

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: loggregator
  version: latest
- name: etcd
  version: latest
- name: consul
  version: latest

instance_groups:
- name: consul
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
    static_ips: [10.244.10.2]
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
          servers: &3
            lan: [10.244.10.2]
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent_cert))"
        agent_key: "((consul_agent_agent_key))"
        ca_cert: "((consul_agent_ca_cert))"
        server_cert: "((consul_agent_server_cert))"
        server_key: "((consul_agent_server_key))"
  - name: metron_agent
    release: loggregator
    properties: &2
      doppler:
        addr: doppler.service.cf.internal
      metron_agent:
        protocols:
        - udp
        deployment: loggregator
        etcd:
          client_cert: "((etcd_client_cert))"
          client_key: "((etcd_client_key))"
      metron_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_ca_cert))"
          metron:
            cert: "((metron_agent_tls_client_cert))"
            key: "((metron_agent_tls_client_key))"
        etcd:
          require_ssl: true
          ca_cert: "((etcd_ca_cert))"
          machines: [etcd.service.cf.internal]
  update:
    serial: true
    max_in_flight: 1

- name: loggregator-acceptance-tests
  azs:
  - z1
  instances: 1
  vm_type: common
  stemcell: default
  lifecycle: errand
  networks:
  - name: loggregator
  jobs:
  - name: loggregator-acceptance-tests
    release: loggregator
    properties:
      traffic_controller:
        disable_access_control: true
      loggregator:
        etcd:
          require_ssl: true
          ca_cert: "((etcd_ca_cert))"
          machines: [etcd.service.cf.internal]
      loggregator_acceptance_tests:
        etcd:
          cert: "((etcd_client_cert))"
          key: "((etcd_client_key))"
      loggregator_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
      etcd:
        machines: [etcd.service.cf.internal]
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *3
          services:
            etcd:
              name: etcd
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent_cert))"
        agent_key: "((consul_agent_agent_key))"
        ca_cert: "((consul_agent_ca_cert))"
        server_cert: "((consul_agent_server_cert))"
        server_key: "((consul_agent_server_key))"
  - name: metron_agent
    release: loggregator
    properties: *2


- name: etcd
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *3
          services:
            etcd:
              name: etcd
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent_cert))"
        agent_key: "((consul_agent_agent_key))"
        ca_cert: "((consul_agent_ca_cert))"
        server_cert: "((consul_agent_server_cert))"
        server_key: "((consul_agent_server_key))"
  - name: etcd
    release: etcd
    properties:
      etcd:
        advertise_urls_dns_suffix: etcd.service.cf.internal
        cluster:
        - instances: 1
          name: etcd
        machines: [etcd.service.cf.internal]
        peer_require_ssl: true
        require_ssl: true
        ca_cert: "((etcd_ca_cert))"
        client_cert: "((etcd_client_cert))"
        client_key: "((etcd_client_key))"
        server_cert: "((etcd_server_cert))"
        server_key: "((etcd_server_key))"
        peer_ca_cert: "((etcd_peer_ca_cert))"
        peer_cert: "((etcd_peer_cert))"
        peer_key: "((etcd_peer_key))"
  - name: etcd_metrics_server
    release: etcd
    properties:
      etcd_metrics_server:
        etcd:
          dns_suffix: etcd.service.cf.internal
          require_ssl: true
          ca_cert: "((etcd_ca_cert))"
          client_cert: "((etcd_client_cert))"
          client_key: "((etcd_client_key))"
  - name: metron_agent
    release: loggregator
    properties: *2
  update:
    serial: true
    max_in_flight: 1

- name: doppler
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *3
          services:
            doppler:
              name: doppler
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent_cert))"
        agent_key: "((consul_agent_agent_key))"
        ca_cert: "((consul_agent_ca_cert))"
        server_cert: "((consul_agent_server_cert))"
        server_key: "((consul_agent_server_key))"
  - name: doppler
    release: loggregator
    properties:
      doppler:
        etcd:
          client_cert: "((etcd_client_cert))"
          client_key: "((etcd_client_key))"
        syslog_skip_cert_verify: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_ca_cert))"
          doppler:
            cert: "((loggregator_tls_doppler_cert))"
            key: "((loggregator_tls_doppler_key))"
        etcd:
          require_ssl: true
          ca_cert: "((etcd_ca_cert))"
          machines: [etcd.service.cf.internal]
      doppler_endpoint:
        shared_secret: "((dropsonde_shared_secret))"
  - name: metron_agent
    release: loggregator
    properties: *2

- name: log-api
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: common
  stemcell: default
  networks:
  - name: loggregator
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *3
          services:
            loggregator_trafficcontroller: {}
        require_ssl: true
        encrypt_keys: "((consul_encrypt_keys))"
        agent_cert: "((consul_agent_cert))"
        agent_key: "((consul_agent_agent_key))"
        ca_cert: "((consul_agent_ca_cert))"
        server_cert: "((consul_agent_server_cert))"
        server_key: "((consul_agent_server_key))"
  - name: loggregator_trafficcontroller
    release: loggregator
    properties:
      cc:
        srv_api_uri: ""
      uaa:
        url: ""
      system_domain: unused
      traffic_controller:
        disable_access_control: true
        etcd:
          client_cert: "((etcd_client_cert))"
          client_key: "((etcd_client_key))"
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_ca_cert))"
          trafficcontroller:
            cert: "((loggregator_tls_tc_cert))"
            key: "((loggregator_tls_tc_key))"
        etcd:
          require_ssl: true
          ca_cert: "((etcd_ca_cert))"
          machines: [etcd.service.cf.internal]
      ssl:
        skip_cert_verify: false
  - name: metron_agent
    release: loggregator
    properties: *2
  update:
    max_in_flight: 1
    serial: true

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
